services:
  postgres:
    image: 'postgres:16.2-alpine'
    environment:
      - 'POSTGRES_DB=spring_monolith'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'

    volumes:
      - /c/tmp/postgres_data:/var/lib/postgresql/data

volumes:
  postgres:
